### ISSUE TITLE
IReadOnlyDictionary support

### ISSUE THREAD

**Issue by Jaben** [csainty/Veil#12]
Veil doesn't appear to have support for the IReadOnlyDictionary interface:

```
Veil.VeilParserException: Unable to parse model expression 'AppName' againt model 'IReadOnlyDictionary`2'
   at Veil.Handlebars.HandlebarsExpressionParser.ParseAgainstModel(Type modelType, String expression, ExpressionScope expressionScope)
   at Veil.Handlebars.HandlebarsExpressionParser.ParseAgainstModel(Type modelType, String expression, ExpressionScope expressionScope)
   at Veil.Handlebars.HandlebarsExpressionParser.ParseAgainstModel(Type modelType, String expression, ExpressionScope expressionScope)
   at Veil.Handlebars.HandlebarsParser.HandleExpression(HandlebarsParserState state)
   at Veil.Handlebars.HandlebarsParser.Parse(TextReader templateReader, Type modelType)
   at Veil.VeilEngine.Compile[T](String parserKey, TextReader templateContents)
```

**Comment by csainty** [comment]
This should be working on v0.3.0
I'll close the issue, re-open if it is still causing you problems
