### ISSUE TITLE
Security exception

### ISSUE THREAD

**Issue by wallymathieu** [csainty/Veil#15]
I get the following exception when testing the library:
```
An exception of type 'System.Security.VerificationException' occurred in Veil.dll but was not handled in user code
```
The code can be found on the branch [veil_handlebar] (https://github.com/wallymathieu/isop/tree/veil_handlebar)

and a sample failing build on [appveyor](https://ci.appveyor.com/project/wallymathieu/isop/build/1.0.79)

```
   at _DynamicMethod1(TextWriter , MissingArgument )
   at _DynamicMethod1(TextWriter , Object , Object )
   at Veil.VeilEngine.<>c__DisplayClass1.<CompileNonGeneric>b__0(TextWriter w, Object m) in c:\Projects\Veil\Src\Veil\VeilEngine.cs:line 74
   at CallSite.Target(Closure , CallSite , Action`2 , StreamWriter , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Nancy.ViewEngines.Veil.VeilViewEngine.<>c__DisplayClassa.<RenderView>b__9(Stream s) in c:\Projects\Veil\Src\Nancy.ViewEngines.Veil\VeilViewEngine.cs:line 51
   at Nancy.Responses.MaterialisingResponse.PreExecute(NancyContext context)
```

**Comment by csainty** [comment]
I need to properly publish my latest changes to Veil. It will be interesting to see if they make a change here. I moved from direct IL generation to using System.Linq.Expressions - so the framework will be handling more edge cases for me.

I'll make some time soon to do that, the code is all done, there was just something odd happening with the build that I did not debug yet.

**Comment by wallymathieu** [comment]
Looks like a more recent version of Veil solves this problem (a veil fork on myget). Should we close this?

**Comment by csainty** [comment]
Okay great.
We can close and once I sort out the build issue I am having with the latest version I can publish it.
